<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="logic.js"></script>
    <title>Page de test</title>
</head>
<body>

    <table>
        <tr>
            <th>Heure</th>
            <th>1</th>
            <th>2</th>
            <th>3</th>
            <th>4</th>
            <th>5</th>
            <th>6</th>
            <th>7</th>
            <th>8</th>
            <th>9</th>
            <th>10</th>
            <th>11</th>
            <th>12</th>
            <th>13</th>
            <th>14</th>
            <th>15</th>
            <th>16</th>
            <th>17</th>
            <th>18</th>
            <th>19</th>
            <th>20</th>
            <th>21</th>
            <th>22</th>
            <th>23</th>
            <th>24</th>

        </tr>
        <tr>
            <td>Temp Int (°C)</td>
            <td>28</td>
            <td>28</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>28</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>

        </tr>
        <tr>
            <td>Temp Ext (°C)</td>
            <td>28</td>
            <td>28</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>28</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
            <td>27</td>
        </tr>
        <tr>
            <td>Humidité (%)</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
        </tr>
        <tr>
            <td>Pression (hPa)</td>
            <td>1057</td>
            <td>1054</td>
            <td>1005</td>
            <td>0056</td>
            <td>0000</td>
            <td>1534</td>
            <td>1278</td>
            <td>1027</td>
            <td>1028</td>
            <td>2286</td>
            <td>7675</td>
            <td>5567</td>
            <td>990</td>
            <td>6500</td>
            <td>6042</td>
            <td>6350</td>
            <td>3354</td>
            <td>3754</td>
            <td>6054</td>
            <td>6340</td>
            <td>6650</td>
            <td>6550</td>
            <td>5550</td>
            <td>5555</td>
        </tr>
    </table>
</body>
</html>